sudo: false

language: node_js

node_js:
  - 4
  - 6
  - 7

script:
  - yarn run depcheck
  - yarn run lint
  - yarn run test

before_deploy:
  - ./node_modules/.bin/patch-version

deploy:
  - provider: npm
    skip_cleanup: true
    email: lijunle@gmail.com
    api_key:
      secure: k8q2IULc0k1+j3YZW2rM1hzjapWfML+MPSuQuo4p1c0XD2LK5HRtR/733hFR/YOeJtW5MdJ/JokRZCMrJEwVRlVnfUPDpYurSDC33KXAuSGjXUJ24cAZE8JVZfn1YwChX8br4xSF4aB2nWrOwM2XgilPaT4prY38Qs5nerZp8nml47xbTVzp5nnS+EU84q8zs6EUt5HscBxtOc+EzvvbI2cBoPguFC5xLjWuKYGKdK+V2a1BrMKDbzo4ZgMxXAJdBKsVeowvwSthTcB0JeXFMItPEAVwiH2gjCwOOOEUU7A24/lB1bo04fnbvh3Drhxk2Ch2prDCQGo+X+ubHVxqV4rlm66O1XEz9fasA0u17OzQIuonxdhoVr7SNl3WYwOGJ+8nMZ30y4SJJhwzPKjl4ErUoADtM0084cQQYd5Fmq4BFYSUBPA3ANxt15qlRYvOr9pP0LBwFbccmiHXWSlcPZuKE+vYhtuywYVGrFY5VvrGlz1pcu7NSrhM46wzvJbXJRScsqmIHX7cTCWqOsjCSVOTceO3zvfX1xoJGlYvIYNFgmFNYy+vg0vUQ/Sr8s2f3wSoMkQJLbCCvgnX12v7wfgmfIbBnrIhH+Yf7ndvAcYSbMpgaOUG3B+O46NMOJanJuHi+Fp+O1yqggK7sb1NxwP04W+3uqu27TQinljFZq0=
    on:
      tags: true
      node: 6
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: kka7agH7sLzS5yNyHB/nnHgwuDF8+vecfzke9MNdDgQdpf0yzOOcHzv92QeOK7x94YvlthfHQfZH7qFsQTeKL3XXDuBuB4iTqrHNBJaYybuhFci+v6hPqQUypLeoHfYtndRfPE/hcP9F8kKVTjKhrczUNOVgdMxLrF9n6PZv7apjm2GMRcIwXKcHu1FCG74+yosu61JeY2tn6kR0aDz3ITcI2S8hsLz5Nf8YjvXYKQoZbBBEUcT1/G1TMZlfJOYyd2tJ9oXLv81bXiURpIJapDuZYFUasUuaiPqzDSiBBNuUFl38VrPyDYs5dMvwqKEkjQRWnLpVzMIULr5hK04UKoxTiwC0MpAkKWil1v+O7YjngT22J4/q7sDIBAIs0Api99BS+8lmx6lJ0qPZBXmFTqUHDYVA1R8JXV3mbiREZfL74KeYkSHP8RCoGBX05tCjxQTDE3nuxOOnrSjKtufCztW2Ua3U1sTPhh5wfsbCtag/52/V4tHWFlL/p1WddURBF8ZfIWFQMcin5HmAUzyYFBZ4ECOmLJL6iYYI/8kbQJprRLHrHugRxu7Dr0Uh6pO4zdD/UOnNjvWaug8f5ph5ugIOhf5UlFgCVDGgEy5TWWCPDOKmlPsflOYyjtVnA6YwqNvIyRx/9DA2YV/UWHyLbNPi4jyWRNMWDhuGDJoZHV8=
    on:
      tags: true
      node: 6
